<?php
// get_explore.php

// 1. Turn off error printing (logs errors instead of printing them)
error_reporting(E_ALL); 
ini_set('display_errors', 0); 

// 2. Start buffering output
ob_start();

include 'db_connect.php'; 

// 3. Clear any text/whitespace generated by the include above
ob_clean(); 

header('Content-Type: application/json');

$response = ["status" => 0, "error" => "Unknown error"];

// Check Connection
if (!$conn) {
    echo json_encode(["status" => 0, "error" => "Database connection failed"]);
    exit();
}

// Fetch Data
$sql = "SELECT * FROM explore_deeper LIMIT 1";
$result = $conn->query($sql);

if ($result && $result->num_rows > 0) {
    $data = $result->fetch_assoc();
    echo json_encode($data);
} else {
    // If table is empty, return status 0 (Hidden)
    echo json_encode(["status" => 0, "error" => "Table is empty"]);
}

$conn->close();
?>